---
- name: Configure shopt Preferences.
  lineinfile:
    dest: /etc/bashrc
    line: "{{item}}"
    create: yes
  with_items: "{{shopt_options}}"

- name: Configure Bash Completion.
  blockinfile:
    dest: /etc/bashrc
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
     if ! shopt -oq posix; then
        if [ -f /usr/share/bash-completion/bash_completion ]; then
           . /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
           . /etc/bash_completion
        fi
     fi

- name: Enable EPEL Repositories.
  package:
    name: epel-release
    state: present
  when: common_epel_enabled and ansible_distribution == "CentOS"
