---
- name: Concatenate Scripting Variables.
  set_fact:
    common_scripting_scripts: "{% if common_scripting_scripts_global is defined %}{{ common_scripting_scripts_global }}{% endif %}{% if common_scripting_scripts_os is defined %}+ {{ common_os_users_present }}{% endif %}{% if common_scripting_scripts_system is defined %}+ {{ common_scripting_scripts_system }}{% endif %}{% if common_scripting_scripts_stage is defined %}+ {{ common_scripting_scripts_stage }}{% endif %}{% if common_scripting_scripts_role is defined %}+ {{ common_scripting_scripts_role }}{% endif %}"

- name: Create scripts path.
  file:
    path: "{{ common_scripting_path }}"
    state: directory
    owner: root
    group: root
    mode: 0740

- name: Upload Scripts.
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ common_scripting_scripts }}"
  when: common_scripting_scripts is defined

- name: Remove Scripts.
  file:
    path: "{{ item.dest }}"
    state: "{{ item.state }}"
  with_items: "{{ common_scripting_scripts }}"
  when: common_scripting_scripts is defined and item.state == "absent"

- name: Create config path.
  file:
    path: "{{ common_config_path }}"
    state: directory
    owner: root
    group: root
    mode: 0740
