---
- name: Configure shopt preferences.
  lineinfile:
   dest: /etc/bash.bashrc
   line: "{{ item }}"
   create: 'true'
  with_items: "{{ shopt_options }}"

- name: Configure bash completion.
  blockinfile:
   dest: /etc/bash.bashrc
   create: 'true'
   marker: "# {mark} ANSIBLE MANAGED BLOCK"
   content: |
    if ! shopt -oq posix; then
       if [ -f /usr/share/bash-completion/bash_completion ]; then
          . /usr/share/bash-completion/bash_completion
       elif [ -f /etc/bash_completion ]; then
          . /etc/bash_completion
       fi
    fi

- name: Workaround - Install python-xml.
  shell: zypper in -y python-xml
  args:
    warn: false
  when: ansible_distribution == "opensuse Leap" and ansible_distribution_major_version == "15"
